
import React, { useState } from 'react';
import { FileDown, Check, FileText, Download } from 'lucide-react';
import { SearchResult } from '../types';

interface WordResultCardProps {
  result: SearchResult;
}

const WordResultCard: React.FC<WordResultCardProps> = ({ result }) => {
  const [downloading, setDownloading] = useState(false);

  const handleDownload = () => {
    setDownloading(true);
    
    // Create HTML template with Word-compatible styles
    const header = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>Exported Research Manuscript</title>
      <style>
        body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.5; color: #000; }
        h1 { font-size: 16pt; font-weight: bold; margin-bottom: 12pt; text-align: center; }
        h2 { font-size: 14pt; font-weight: bold; margin-top: 18pt; margin-bottom: 6pt; border-bottom: 1px solid #ccc; }
        p { margin-bottom: 10pt; text-indent: 0.5in; }
        ul, ol { margin-bottom: 10pt; }
        li { margin-bottom: 4pt; }
        table { border-collapse: collapse; width: 100%; margin: 12pt 0; }
        th, td { border: 1px solid #000; padding: 6pt; text-align: left; font-size: 11pt; }
        .footer { font-size: 9pt; color: #666; margin-top: 30pt; text-align: center; border-top: 1px solid #eee; padding-top: 10pt; }
      </style>
      </head><body>
    `;
    
    const footer = `
      <div class='footer'>
        Generated by BioSearch Architect | Biomaterials Research Support
      </div>
      </body></html>
    `;

    // Basic Markdown to HTML conversion for Word
    let formattedContent = result.content
      .replace(/## (.*)/g, '<h2>$1</h2>')
      .replace(/# (.*)/g, '<h1>$1</h1>')
      .replace(/- \*\*(.*?):\*\*\s*(.*)/g, '<li><strong>$1:</strong> $2</li>')
      .replace(/- (.*)/g, '<li>$1</li>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

    // Wrap in paragraph if not already
    if (!formattedContent.startsWith('<')) {
        formattedContent = '<p>' + formattedContent + '</p>';
    }

    const fullHtml = header + formattedContent + footer;
    
    // Create a Blob from the HTML content
    const blob = new Blob(['\ufeff', fullHtml], {
      type: 'application/msword'
    });
    
    // Trigger download
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `BioSearch_Manuscript_${new Date().getTime()}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setTimeout(() => setDownloading(false), 1500);
  };

  return (
    <div className="w-full bg-white rounded-2xl shadow-lg border border-blue-100 overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 px-6 py-4 border-b border-blue-100 flex justify-between items-center">
        <div className="flex items-center gap-2">
            <div className="bg-white p-1.5 rounded-md shadow-sm border border-blue-100 text-blue-600">
                <FileText className="w-4 h-4" />
            </div>
            <h3 className="font-semibold text-slate-800">Manuscript Architect Preview</h3>
        </div>
        <div className="text-xs text-blue-700/70 font-mono bg-blue-50 px-2 py-1 rounded border border-blue-100">
            Word Ready Layout
        </div>
      </div>
      
      <div className="p-8">
        <div className="bg-slate-50 border-2 border-dashed border-slate-200 rounded-2xl p-8 mb-8 relative group">
            {/* Document Preview Mock */}
            <div className="bg-white shadow-2xl rounded-sm p-10 max-w-lg mx-auto transform group-hover:scale-[1.02] transition-transform duration-500">
                <div className="w-3/4 h-6 bg-slate-200 mb-6 mx-auto rounded"></div>
                <div className="w-1/2 h-3 bg-slate-100 mb-10 mx-auto rounded"></div>
                
                <div className="space-y-3 mb-8">
                    <div className="w-full h-2 bg-slate-50 rounded"></div>
                    <div className="w-full h-2 bg-slate-50 rounded"></div>
                    <div className="w-5/6 h-2 bg-slate-50 rounded"></div>
                </div>

                <div className="w-1/3 h-4 bg-slate-200 mb-4 rounded"></div>
                <div className="space-y-3">
                    <div className="w-full h-2 bg-slate-50 rounded"></div>
                    <div className="w-4/5 h-2 bg-slate-50 rounded"></div>
                </div>

                <div className="absolute inset-0 bg-gradient-to-t from-white/90 via-transparent to-transparent"></div>
            </div>
            
            <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-white/40 backdrop-blur-[1px]">
                <button 
                  onClick={handleDownload}
                  className="bg-indigo-600 text-white px-6 py-3 rounded-full font-bold shadow-xl flex items-center gap-2 transform translate-y-4 group-hover:translate-y-0 transition-transform"
                >
                   <Download className="w-5 h-5" />
                   Download Full Draft
                </button>
            </div>
        </div>

        <div className="flex flex-col items-center text-center max-w-sm mx-auto">
            <h4 className="font-bold text-slate-900 mb-2">Structure Generated</h4>
            <p className="text-sm text-slate-500 mb-8 leading-relaxed">
                Your research content has been structured into a publication-ready layout with academic formatting.
            </p>
            
            <button
                onClick={handleDownload}
                disabled={downloading}
                className={`
                    w-full flex items-center justify-center gap-3 py-4 rounded-xl font-bold text-lg transition-all
                    ${downloading 
                        ? 'bg-green-500 text-white' 
                        : 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-lg shadow-indigo-100'
                    }
                `}
            >
                {downloading ? (
                    <>
                        <Check className="w-6 h-6" />
                        <span>Ready! Check Downloads</span>
                    </>
                ) : (
                    <>
                        <FileDown className="w-6 h-6" />
                        <span>Download as Word (.doc)</span>
                    </>
                )}
            </button>
        </div>
      </div>
    </div>
  );
};

export default WordResultCard;
